### ISSUE TITLE
Feedback: lack of setter methods on mutable object properties makes upgrades difficult, .toBuilder() methods on objects new parent objects but reuse children objects

### ISSUE THREAD

**Issue by jfinci** [square/square-java-sdk#13]
Many objects, including orders, catalog, and customers, are mutable-  forcing the developer to use a builder for these is inconvenient and makes upgrades difficult.  

Furthermore, the .toBuilder() methods create new parent objects but reference existing children object- the inconsistency feels a bit off.  

```
var itemData = new CatalogItem.Builder().build();
var object = new CatalogObject.Builder(null, null)
    .itemData(itemData)
    .build();

CatalogObject modified = object.toBuilder().build();

//this feels funny
assert modified != object;
assert object.getItemData() == modified.getItemData();
```

**Comment by sseaman** [comment]
Thanks for providing this feedback. We are investigating our use of the builder pattern.

**Comment by sseaman** [comment]
We'll be leaving this the way it is to support immutability.
