### ISSUE TITLE
Customer builder shouldn't require `created_at`, `updated_at` or `id`

### ISSUE THREAD

**Issue by jfinci** [square/square-java-sdk#14]
Creating a customer with the Square API requires one of the following properties: 

`given_name`
`family_name`
`company_name`
`email_address`
`phone_number`

[Customers technical reference](https://developer.squareup.com/reference/square/customers-api/create-customer)

however the builder requires these `created_at`, `updated_at` and `id` when building a new customer object.

This lends to:
```
var customer = new Customer.Builder(null, null, null)
    .build();
```

I recommend removing all builder parameters from all objects

**Comment by sseaman** [comment]
Builder parameters exist whenever a field is required in the object.  This ensure that the fields are not missed when only using a pattern such as setters.   The customer object had a bug (thank you for pointing that out) and should be fixed in the latest version of the SDK.

**Comment by jfinci** [comment]
you've stated: `Builder parameters exist whenever a field is required in the object.`

But these fields *aren't* required in the object.  They're required in the API.  typically I expect builder or constructor parameters to be required only when certain client functionality expects them.  client functionality is unaffected by the existence or non-existence of these parameters.

**Comment by jfinci** [comment]
I understand the desire to give developers more clues during implementation and how that lends us to believe constructor and builder parameters should accept them but it ultimately feels misguided and limits when objects can be created at the expense of the experienced Square platform developer
