### ISSUE TITLE
OkClient implements broken multi-threaded synchronization method

### ISSUE THREAD

**Issue by jfinci** [square/square-java-sdk#15]
https://github.com/square/square-java-sdk/blob/master/src/main/java/com/squareup/square/http/client/OkClient.java

Blog post explaining the issue: http://jeremymanson.blogspot.com/2008/05/double-checked-locking.html

Summary:
JIT compiler can reorder code such that the client class field is set outside of the synchronized block

**Comment by sseaman** [comment]
We're looking into this.  Thanks for reporting.

**Comment by sseaman** [comment]
Should be fixed in SDK that was released on July 22nd.
